### ISSUE TITLE
Does the script work also on Freemat?

### ISSUE THREAD

**Issue by marksev1** [JorgeGT/PlotRTL1090#1]
Freemat, a free and opensource alternative to Matlab, alegdly has good compatibility with Matlab scripts, do you maybe know if it would work?

**Comment by JorgeGT** [comment]
Uhm, I haven't tried to use alternatives to MATLAB (Octave, Freemat, etc.) but I think this particular script will work with them, because it uses:
- A compiled *.mex function to decode JSON
- The mapping toolbox to perform coordinate conversion and read SHP files

However if you find a workaround around these (other JSON decoding library, other way to display shapefiles, etc.) you should get a basic functionality, as the basic operation is first log data, and then plot them as a 3D point cloud, which almost any clone of MATLAB can do. Be sure to come back with the results if you try! =)

**Comment by marksev1** [comment]
Lol Jorge I haven't yet tried to use your script, was a long time before I asked about the compatibility...

Now I'd like to try and since I'm not a coder I need a few question on how the workflow should be. Can you tell me whats your workflow in using the stuff in Matlab and then I'll try to replicate in Freemat. I'd first like to try with your example data, which is coords.mat right?

Btw I can open plotRTL1090.m in Freemat, when I try to "play" it it throws an error: that it can't open the coords.mat file.

**Comment by JorgeGT** [comment]
Hi! I haven't really used Freemat, so I don't know if the .mat files can be opened or not! [Here](https://www.dropbox.com/s/1x48xc1h74i615y/coords.csv?dl=1) is the data in CSV format. Anyway, the basic workflow to get the 3D plot is pretty simple:
- Have a `dump1090` server running at a known and accessible URL like `http://0.0.0.0:8080`
- Have your script periodically read `http://0.0.0.0:8080/data.json`, which will look like this (for each plane):

``` json
[
   {  
      "hex":"400db2",
      "squawk":"4665",
      "flight":"EZY56RV ",
      "lat":39.183609,
      "lon":-0.979694,
      "validposition":1,
      "altitude":30700,
      "vert_rate":896,
      "track":344,
      "validtrack":1,
      "speed":440,
      "messages":175,
      "seen":0
   }
]
```
- Parse this JSON data and get, at least, lat, lon and altitude. Store them in vectors.
- Once you have enough data, plot these three vectors in a 3D scatter graph.
  - Optional: use UTM to convert lat and lon to feet (or meters) if you want no Z distortion
  - Optional: draw bullseye and distances as lines, circles and text labels
  - Optional: get administrative boundaries shapefiles from [Natural Earth](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/)
  - And figure out how select and plot the ones that you want to add to the scene!
- Sequentially rotate the camera around the scene and save each frame to video/gif.
- ???
- Profit!
